package medical.surveyAsd.service.impl;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.poi.ss.usermodel.Sheet;

import medical.framework.file.mapping.CellReaderMapper;
import medical.framework.file.mapping.CellReaderMapperException;
import medical.framework.util.POIUtil;
import medical.surveyAsd.service.SurveyAsdCc3qaVO;

public class SurveyAsdCc3qaCellReaderMapper implements CellReaderMapper<SurveyAsdCc3qaVO>{

	protected final Log logger = LogFactory.getLog(getClass());
	
	@Override
	public SurveyAsdCc3qaVO mapCell(Sheet sheet, int col, int row) 
			throws CellReaderMapperException {
		SurveyAsdCc3qaVO surveyAsdCc3qaVO = new SurveyAsdCc3qaVO();
		try {
			surveyAsdCc3qaVO.setTargetId(POIUtil.getStringCellValue(sheet.getRow(row).getCell(0)).trim().replace("",""));
			surveyAsdCc3qaVO.setPerformCnt(POIUtil.getStringCellValue(sheet.getRow(row).getCell(2)).trim().replace("",""));
			String execDate = POIUtil.getStringCellValue(sheet.getRow(row).getCell(3)).trim().replace("","");
			surveyAsdCc3qaVO.setCc3qaExecDate(execDate.replace("-", ""));
			surveyAsdCc3qaVO.setA1(POIUtil.getStringCellValue(sheet.getRow(row).getCell(4)).trim().replace("",""));		
			surveyAsdCc3qaVO.setA2(POIUtil.getStringCellValue(sheet.getRow(row).getCell(5)).trim().replace("",""));		
			surveyAsdCc3qaVO.setA3(POIUtil.getStringCellValue(sheet.getRow(row).getCell(6)).trim().replace("",""));		
			surveyAsdCc3qaVO.setA4(POIUtil.getStringCellValue(sheet.getRow(row).getCell(7)).trim().replace("",""));		
			surveyAsdCc3qaVO.setA5(POIUtil.getStringCellValue(sheet.getRow(row).getCell(8)).trim().replace("",""));		
			surveyAsdCc3qaVO.setA6(POIUtil.getStringCellValue(sheet.getRow(row).getCell(9)).trim().replace("",""));		
			surveyAsdCc3qaVO.setA7(POIUtil.getStringCellValue(sheet.getRow(row).getCell(10)).trim().replace("",""));		
			surveyAsdCc3qaVO.setA8(POIUtil.getStringCellValue(sheet.getRow(row).getCell(11)).trim().replace("",""));		
			surveyAsdCc3qaVO.setA9(POIUtil.getStringCellValue(sheet.getRow(row).getCell(12)).trim().replace("",""));		
			surveyAsdCc3qaVO.setA10(POIUtil.getStringCellValue(sheet.getRow(row).getCell(13)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA11(POIUtil.getStringCellValue(sheet.getRow(row).getCell(14)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA12(POIUtil.getStringCellValue(sheet.getRow(row).getCell(15)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA13(POIUtil.getStringCellValue(sheet.getRow(row).getCell(16)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA14(POIUtil.getStringCellValue(sheet.getRow(row).getCell(17)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA15(POIUtil.getStringCellValue(sheet.getRow(row).getCell(18)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA16(POIUtil.getStringCellValue(sheet.getRow(row).getCell(19)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA17(POIUtil.getStringCellValue(sheet.getRow(row).getCell(20)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA18(POIUtil.getStringCellValue(sheet.getRow(row).getCell(21)).trim().replace("",""));			
			surveyAsdCc3qaVO.setA19(POIUtil.getStringCellValue(sheet.getRow(row).getCell(22)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA20(POIUtil.getStringCellValue(sheet.getRow(row).getCell(23)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA21(POIUtil.getStringCellValue(sheet.getRow(row).getCell(24)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA22(POIUtil.getStringCellValue(sheet.getRow(row).getCell(25)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA23(POIUtil.getStringCellValue(sheet.getRow(row).getCell(26)).trim().replace("",""));	
			surveyAsdCc3qaVO.setA24(POIUtil.getStringCellValue(sheet.getRow(row).getCell(27)).trim().replace("",""));
			surveyAsdCc3qaVO.setA25(POIUtil.getStringCellValue(sheet.getRow(row).getCell(28)).trim().replace("",""));
			surveyAsdCc3qaVO.setA26(POIUtil.getStringCellValue(sheet.getRow(row).getCell(29)).trim().replace("",""));
			surveyAsdCc3qaVO.setA27(POIUtil.getStringCellValue(sheet.getRow(row).getCell(30)).trim().replace("",""));
			surveyAsdCc3qaVO.setA28(POIUtil.getStringCellValue(sheet.getRow(row).getCell(31)).trim().replace("",""));
			surveyAsdCc3qaVO.setA29(POIUtil.getStringCellValue(sheet.getRow(row).getCell(32)).trim().replace("",""));
			surveyAsdCc3qaVO.setA30(POIUtil.getStringCellValue(sheet.getRow(row).getCell(33)).trim().replace("",""));
			surveyAsdCc3qaVO.setA31(POIUtil.getStringCellValue(sheet.getRow(row).getCell(34)).trim().replace("",""));
			surveyAsdCc3qaVO.setA32(POIUtil.getStringCellValue(sheet.getRow(row).getCell(35)).trim().replace("",""));
			surveyAsdCc3qaVO.setA33(POIUtil.getStringCellValue(sheet.getRow(row).getCell(36)).trim().replace("",""));
			surveyAsdCc3qaVO.setA34(POIUtil.getStringCellValue(sheet.getRow(row).getCell(37)).trim().replace("",""));
			surveyAsdCc3qaVO.setA35(POIUtil.getStringCellValue(sheet.getRow(row).getCell(38)).trim().replace("",""));
			surveyAsdCc3qaVO.setA36(POIUtil.getStringCellValue(sheet.getRow(row).getCell(39)).trim().replace("",""));
			surveyAsdCc3qaVO.setA37(POIUtil.getStringCellValue(sheet.getRow(row).getCell(40)).trim().replace("",""));
			surveyAsdCc3qaVO.setA38(POIUtil.getStringCellValue(sheet.getRow(row).getCell(41)).trim().replace("",""));
			surveyAsdCc3qaVO.setA39(POIUtil.getStringCellValue(sheet.getRow(row).getCell(42)).trim().replace("",""));
			surveyAsdCc3qaVO.setA40(POIUtil.getStringCellValue(sheet.getRow(row).getCell(43)).trim().replace("",""));
			surveyAsdCc3qaVO.setA41(POIUtil.getStringCellValue(sheet.getRow(row).getCell(44)).trim().replace("",""));
			surveyAsdCc3qaVO.setA42(POIUtil.getStringCellValue(sheet.getRow(row).getCell(45)).trim().replace("",""));
			surveyAsdCc3qaVO.setA43(POIUtil.getStringCellValue(sheet.getRow(row).getCell(46)).trim().replace("",""));
			surveyAsdCc3qaVO.setA44(POIUtil.getStringCellValue(sheet.getRow(row).getCell(47)).trim().replace("",""));
			surveyAsdCc3qaVO.setA45(POIUtil.getStringCellValue(sheet.getRow(row).getCell(48)).trim().replace("",""));
			surveyAsdCc3qaVO.setA46(POIUtil.getStringCellValue(sheet.getRow(row).getCell(49)).trim().replace("",""));
			surveyAsdCc3qaVO.setA47(POIUtil.getStringCellValue(sheet.getRow(row).getCell(50)).trim().replace("",""));
			surveyAsdCc3qaVO.setA48(POIUtil.getStringCellValue(sheet.getRow(row).getCell(51)).trim().replace("",""));
			surveyAsdCc3qaVO.setA49(POIUtil.getStringCellValue(sheet.getRow(row).getCell(52)).trim().replace("",""));
			surveyAsdCc3qaVO.setA50(POIUtil.getStringCellValue(sheet.getRow(row).getCell(53)).trim().replace("",""));
			surveyAsdCc3qaVO.setA51(POIUtil.getStringCellValue(sheet.getRow(row).getCell(54)).trim().replace("",""));
			surveyAsdCc3qaVO.setA52(POIUtil.getStringCellValue(sheet.getRow(row).getCell(55)).trim().replace("",""));
			surveyAsdCc3qaVO.setA53(POIUtil.getStringCellValue(sheet.getRow(row).getCell(56)).trim().replace("",""));
			surveyAsdCc3qaVO.setA54(POIUtil.getStringCellValue(sheet.getRow(row).getCell(57)).trim().replace("",""));
			surveyAsdCc3qaVO.setA55(POIUtil.getStringCellValue(sheet.getRow(row).getCell(58)).trim().replace("",""));
			surveyAsdCc3qaVO.setA56(POIUtil.getStringCellValue(sheet.getRow(row).getCell(59)).trim().replace("",""));
			surveyAsdCc3qaVO.setA57(POIUtil.getStringCellValue(sheet.getRow(row).getCell(60)).trim().replace("",""));
			surveyAsdCc3qaVO.setA58(POIUtil.getStringCellValue(sheet.getRow(row).getCell(61)).trim().replace("",""));
			surveyAsdCc3qaVO.setA59(POIUtil.getStringCellValue(sheet.getRow(row).getCell(62)).trim().replace("",""));
			surveyAsdCc3qaVO.setA60(POIUtil.getStringCellValue(sheet.getRow(row).getCell(63)).trim().replace("",""));
			surveyAsdCc3qaVO.setScoreA(POIUtil.getStringCellValue(sheet.getRow(row).getCell(64)).trim().replace("",""));
			
			surveyAsdCc3qaVO.setB1(POIUtil.getStringCellValue(sheet.getRow(row).getCell(65)).trim().replace("",""));
			surveyAsdCc3qaVO.setB2(POIUtil.getStringCellValue(sheet.getRow(row).getCell(66)).trim().replace("",""));
			surveyAsdCc3qaVO.setB3(POIUtil.getStringCellValue(sheet.getRow(row).getCell(67)).trim().replace("",""));
			surveyAsdCc3qaVO.setB4(POIUtil.getStringCellValue(sheet.getRow(row).getCell(68)).trim().replace("",""));
			surveyAsdCc3qaVO.setB5(POIUtil.getStringCellValue(sheet.getRow(row).getCell(69)).trim().replace("",""));
			surveyAsdCc3qaVO.setB6(POIUtil.getStringCellValue(sheet.getRow(row).getCell(70)).trim().replace("",""));
			surveyAsdCc3qaVO.setB7(POIUtil.getStringCellValue(sheet.getRow(row).getCell(71)).trim().replace("",""));
			surveyAsdCc3qaVO.setB8(POIUtil.getStringCellValue(sheet.getRow(row).getCell(72)).trim().replace("",""));
			surveyAsdCc3qaVO.setB9(POIUtil.getStringCellValue(sheet.getRow(row).getCell(73)).trim().replace("",""));
			surveyAsdCc3qaVO.setB10(POIUtil.getStringCellValue(sheet.getRow(row).getCell(74)).trim().replace("",""));
			surveyAsdCc3qaVO.setB11(POIUtil.getStringCellValue(sheet.getRow(row).getCell(75)).trim().replace("",""));
			surveyAsdCc3qaVO.setB12(POIUtil.getStringCellValue(sheet.getRow(row).getCell(76)).trim().replace("",""));
			surveyAsdCc3qaVO.setB13(POIUtil.getStringCellValue(sheet.getRow(row).getCell(77)).trim().replace("",""));
			surveyAsdCc3qaVO.setB14(POIUtil.getStringCellValue(sheet.getRow(row).getCell(78)).trim().replace("",""));
			surveyAsdCc3qaVO.setB15(POIUtil.getStringCellValue(sheet.getRow(row).getCell(79)).trim().replace("",""));
			surveyAsdCc3qaVO.setB16(POIUtil.getStringCellValue(sheet.getRow(row).getCell(80)).trim().replace("",""));
			surveyAsdCc3qaVO.setB17(POIUtil.getStringCellValue(sheet.getRow(row).getCell(81)).trim().replace("",""));
			surveyAsdCc3qaVO.setB18(POIUtil.getStringCellValue(sheet.getRow(row).getCell(82)).trim().replace("",""));
			surveyAsdCc3qaVO.setB19(POIUtil.getStringCellValue(sheet.getRow(row).getCell(83)).trim().replace("",""));
			surveyAsdCc3qaVO.setB20(POIUtil.getStringCellValue(sheet.getRow(row).getCell(84)).trim().replace("",""));
			surveyAsdCc3qaVO.setB21(POIUtil.getStringCellValue(sheet.getRow(row).getCell(85)).trim().replace("",""));
			surveyAsdCc3qaVO.setB22(POIUtil.getStringCellValue(sheet.getRow(row).getCell(86)).trim().replace("",""));
			surveyAsdCc3qaVO.setB23(POIUtil.getStringCellValue(sheet.getRow(row).getCell(87)).trim().replace("",""));
			surveyAsdCc3qaVO.setB24(POIUtil.getStringCellValue(sheet.getRow(row).getCell(88)).trim().replace("",""));
			surveyAsdCc3qaVO.setB25(POIUtil.getStringCellValue(sheet.getRow(row).getCell(89)).trim().replace("",""));
			surveyAsdCc3qaVO.setB26(POIUtil.getStringCellValue(sheet.getRow(row).getCell(90)).trim().replace("",""));
			surveyAsdCc3qaVO.setB27(POIUtil.getStringCellValue(sheet.getRow(row).getCell(91)).trim().replace("",""));
			surveyAsdCc3qaVO.setB28(POIUtil.getStringCellValue(sheet.getRow(row).getCell(92)).trim().replace("",""));
			surveyAsdCc3qaVO.setB29(POIUtil.getStringCellValue(sheet.getRow(row).getCell(93)).trim().replace("",""));
			surveyAsdCc3qaVO.setB30(POIUtil.getStringCellValue(sheet.getRow(row).getCell(94)).trim().replace("",""));
			surveyAsdCc3qaVO.setB31(POIUtil.getStringCellValue(sheet.getRow(row).getCell(95)).trim().replace("",""));
			surveyAsdCc3qaVO.setB32(POIUtil.getStringCellValue(sheet.getRow(row).getCell(96)).trim().replace("",""));
			surveyAsdCc3qaVO.setB33(POIUtil.getStringCellValue(sheet.getRow(row).getCell(97)).trim().replace("",""));
			surveyAsdCc3qaVO.setB34(POIUtil.getStringCellValue(sheet.getRow(row).getCell(98)).trim().replace("",""));
			surveyAsdCc3qaVO.setB35(POIUtil.getStringCellValue(sheet.getRow(row).getCell(99)).trim().replace("",""));
			surveyAsdCc3qaVO.setB36(POIUtil.getStringCellValue(sheet.getRow(row).getCell(100)).trim().replace("",""));
			surveyAsdCc3qaVO.setB37(POIUtil.getStringCellValue(sheet.getRow(row).getCell(101)).trim().replace("",""));
			surveyAsdCc3qaVO.setB38(POIUtil.getStringCellValue(sheet.getRow(row).getCell(102)).trim().replace("",""));
			surveyAsdCc3qaVO.setB39(POIUtil.getStringCellValue(sheet.getRow(row).getCell(103)).trim().replace("",""));
			surveyAsdCc3qaVO.setB40(POIUtil.getStringCellValue(sheet.getRow(row).getCell(104)).trim().replace("",""));
			surveyAsdCc3qaVO.setB41(POIUtil.getStringCellValue(sheet.getRow(row).getCell(105)).trim().replace("",""));
			surveyAsdCc3qaVO.setB42(POIUtil.getStringCellValue(sheet.getRow(row).getCell(106)).trim().replace("",""));
			surveyAsdCc3qaVO.setB43(POIUtil.getStringCellValue(sheet.getRow(row).getCell(107)).trim().replace("",""));
			surveyAsdCc3qaVO.setB44(POIUtil.getStringCellValue(sheet.getRow(row).getCell(108)).trim().replace("",""));
			surveyAsdCc3qaVO.setB45(POIUtil.getStringCellValue(sheet.getRow(row).getCell(109)).trim().replace("",""));
			surveyAsdCc3qaVO.setB46(POIUtil.getStringCellValue(sheet.getRow(row).getCell(110)).trim().replace("",""));
			surveyAsdCc3qaVO.setB47(POIUtil.getStringCellValue(sheet.getRow(row).getCell(111)).trim().replace("",""));
			surveyAsdCc3qaVO.setB48(POIUtil.getStringCellValue(sheet.getRow(row).getCell(112)).trim().replace("",""));
			surveyAsdCc3qaVO.setB49(POIUtil.getStringCellValue(sheet.getRow(row).getCell(113)).trim().replace("",""));
			surveyAsdCc3qaVO.setB50(POIUtil.getStringCellValue(sheet.getRow(row).getCell(114)).trim().replace("",""));
			surveyAsdCc3qaVO.setB51(POIUtil.getStringCellValue(sheet.getRow(row).getCell(115)).trim().replace("",""));
			surveyAsdCc3qaVO.setB52(POIUtil.getStringCellValue(sheet.getRow(row).getCell(116)).trim().replace("",""));
			surveyAsdCc3qaVO.setB53(POIUtil.getStringCellValue(sheet.getRow(row).getCell(117)).trim().replace("",""));
			surveyAsdCc3qaVO.setB54(POIUtil.getStringCellValue(sheet.getRow(row).getCell(118)).trim().replace("",""));
			surveyAsdCc3qaVO.setB55(POIUtil.getStringCellValue(sheet.getRow(row).getCell(119)).trim().replace("",""));
			surveyAsdCc3qaVO.setB56(POIUtil.getStringCellValue(sheet.getRow(row).getCell(120)).trim().replace("",""));
			surveyAsdCc3qaVO.setB57(POIUtil.getStringCellValue(sheet.getRow(row).getCell(121)).trim().replace("",""));
			surveyAsdCc3qaVO.setB58(POIUtil.getStringCellValue(sheet.getRow(row).getCell(122)).trim().replace("",""));
			surveyAsdCc3qaVO.setB59(POIUtil.getStringCellValue(sheet.getRow(row).getCell(123)).trim().replace("",""));
			surveyAsdCc3qaVO.setB60(POIUtil.getStringCellValue(sheet.getRow(row).getCell(124)).trim().replace("",""));
			surveyAsdCc3qaVO.setB61(POIUtil.getStringCellValue(sheet.getRow(row).getCell(125)).trim().replace("",""));
			surveyAsdCc3qaVO.setB62(POIUtil.getStringCellValue(sheet.getRow(row).getCell(126)).trim().replace("",""));
			surveyAsdCc3qaVO.setB63(POIUtil.getStringCellValue(sheet.getRow(row).getCell(127)).trim().replace("",""));
			surveyAsdCc3qaVO.setB64(POIUtil.getStringCellValue(sheet.getRow(row).getCell(128)).trim().replace("",""));
			surveyAsdCc3qaVO.setB65(POIUtil.getStringCellValue(sheet.getRow(row).getCell(129)).trim().replace("",""));
			surveyAsdCc3qaVO.setB66(POIUtil.getStringCellValue(sheet.getRow(row).getCell(130)).trim().replace("",""));
			surveyAsdCc3qaVO.setB67(POIUtil.getStringCellValue(sheet.getRow(row).getCell(131)).trim().replace("",""));
			surveyAsdCc3qaVO.setB68(POIUtil.getStringCellValue(sheet.getRow(row).getCell(132)).trim().replace("",""));
			surveyAsdCc3qaVO.setB69(POIUtil.getStringCellValue(sheet.getRow(row).getCell(133)).trim().replace("",""));
			surveyAsdCc3qaVO.setB70(POIUtil.getStringCellValue(sheet.getRow(row).getCell(134)).trim().replace("",""));
			surveyAsdCc3qaVO.setB71(POIUtil.getStringCellValue(sheet.getRow(row).getCell(135)).trim().replace("",""));
			surveyAsdCc3qaVO.setB72(POIUtil.getStringCellValue(sheet.getRow(row).getCell(136)).trim().replace("",""));
			surveyAsdCc3qaVO.setB73(POIUtil.getStringCellValue(sheet.getRow(row).getCell(137)).trim().replace("",""));
			surveyAsdCc3qaVO.setB74(POIUtil.getStringCellValue(sheet.getRow(row).getCell(138)).trim().replace("",""));
			surveyAsdCc3qaVO.setB75(POIUtil.getStringCellValue(sheet.getRow(row).getCell(139)).trim().replace("",""));
			surveyAsdCc3qaVO.setScoreB(POIUtil.getStringCellValue(sheet.getRow(row).getCell(140)).trim().replace("",""));

			surveyAsdCc3qaVO.setC1(POIUtil.getStringCellValue(sheet.getRow(row).getCell(141)).trim().replace("",""));
			surveyAsdCc3qaVO.setC2(POIUtil.getStringCellValue(sheet.getRow(row).getCell(142)).trim().replace("",""));
			surveyAsdCc3qaVO.setC3(POIUtil.getStringCellValue(sheet.getRow(row).getCell(143)).trim().replace("",""));
			surveyAsdCc3qaVO.setC4(POIUtil.getStringCellValue(sheet.getRow(row).getCell(144)).trim().replace("",""));
			surveyAsdCc3qaVO.setC5(POIUtil.getStringCellValue(sheet.getRow(row).getCell(145)).trim().replace("",""));
			surveyAsdCc3qaVO.setC6(POIUtil.getStringCellValue(sheet.getRow(row).getCell(146)).trim().replace("",""));
			surveyAsdCc3qaVO.setC7(POIUtil.getStringCellValue(sheet.getRow(row).getCell(147)).trim().replace("",""));
			surveyAsdCc3qaVO.setC8(POIUtil.getStringCellValue(sheet.getRow(row).getCell(148)).trim().replace("",""));
			surveyAsdCc3qaVO.setC9(POIUtil.getStringCellValue(sheet.getRow(row).getCell(149)).trim().replace("",""));
			surveyAsdCc3qaVO.setC10(POIUtil.getStringCellValue(sheet.getRow(row).getCell(150)).trim().replace("",""));
			surveyAsdCc3qaVO.setC11(POIUtil.getStringCellValue(sheet.getRow(row).getCell(151)).trim().replace("",""));
			surveyAsdCc3qaVO.setC12(POIUtil.getStringCellValue(sheet.getRow(row).getCell(152)).trim().replace("",""));
			surveyAsdCc3qaVO.setC13(POIUtil.getStringCellValue(sheet.getRow(row).getCell(153)).trim().replace("",""));
			surveyAsdCc3qaVO.setC14(POIUtil.getStringCellValue(sheet.getRow(row).getCell(154)).trim().replace("",""));
			surveyAsdCc3qaVO.setC15(POIUtil.getStringCellValue(sheet.getRow(row).getCell(155)).trim().replace("",""));
			surveyAsdCc3qaVO.setC16(POIUtil.getStringCellValue(sheet.getRow(row).getCell(156)).trim().replace("",""));
			surveyAsdCc3qaVO.setC17(POIUtil.getStringCellValue(sheet.getRow(row).getCell(157)).trim().replace("",""));
			surveyAsdCc3qaVO.setC18(POIUtil.getStringCellValue(sheet.getRow(row).getCell(158)).trim().replace("",""));
			surveyAsdCc3qaVO.setC19(POIUtil.getStringCellValue(sheet.getRow(row).getCell(159)).trim().replace("",""));
			surveyAsdCc3qaVO.setC20(POIUtil.getStringCellValue(sheet.getRow(row).getCell(160)).trim().replace("",""));
			surveyAsdCc3qaVO.setC21(POIUtil.getStringCellValue(sheet.getRow(row).getCell(161)).trim().replace("",""));
			surveyAsdCc3qaVO.setC22(POIUtil.getStringCellValue(sheet.getRow(row).getCell(162)).trim().replace("",""));
			surveyAsdCc3qaVO.setC23(POIUtil.getStringCellValue(sheet.getRow(row).getCell(163)).trim().replace("",""));
			surveyAsdCc3qaVO.setC24(POIUtil.getStringCellValue(sheet.getRow(row).getCell(164)).trim().replace("",""));
			surveyAsdCc3qaVO.setC25(POIUtil.getStringCellValue(sheet.getRow(row).getCell(165)).trim().replace("",""));
			surveyAsdCc3qaVO.setC26(POIUtil.getStringCellValue(sheet.getRow(row).getCell(166)).trim().replace("",""));
			surveyAsdCc3qaVO.setC27(POIUtil.getStringCellValue(sheet.getRow(row).getCell(167)).trim().replace("",""));
			surveyAsdCc3qaVO.setC28(POIUtil.getStringCellValue(sheet.getRow(row).getCell(168)).trim().replace("",""));
			surveyAsdCc3qaVO.setC29(POIUtil.getStringCellValue(sheet.getRow(row).getCell(169)).trim().replace("",""));
			surveyAsdCc3qaVO.setC30(POIUtil.getStringCellValue(sheet.getRow(row).getCell(170)).trim().replace("",""));
			surveyAsdCc3qaVO.setC31(POIUtil.getStringCellValue(sheet.getRow(row).getCell(171)).trim().replace("",""));
			surveyAsdCc3qaVO.setC32(POIUtil.getStringCellValue(sheet.getRow(row).getCell(172)).trim().replace("",""));
			surveyAsdCc3qaVO.setC33(POIUtil.getStringCellValue(sheet.getRow(row).getCell(173)).trim().replace("",""));
			surveyAsdCc3qaVO.setC34(POIUtil.getStringCellValue(sheet.getRow(row).getCell(174)).trim().replace("",""));
			surveyAsdCc3qaVO.setC35(POIUtil.getStringCellValue(sheet.getRow(row).getCell(175)).trim().replace("",""));
			surveyAsdCc3qaVO.setC36(POIUtil.getStringCellValue(sheet.getRow(row).getCell(176)).trim().replace("",""));
			surveyAsdCc3qaVO.setC37(POIUtil.getStringCellValue(sheet.getRow(row).getCell(177)).trim().replace("",""));
			surveyAsdCc3qaVO.setC38(POIUtil.getStringCellValue(sheet.getRow(row).getCell(178)).trim().replace("",""));
			surveyAsdCc3qaVO.setC39(POIUtil.getStringCellValue(sheet.getRow(row).getCell(179)).trim().replace("",""));
			surveyAsdCc3qaVO.setC40(POIUtil.getStringCellValue(sheet.getRow(row).getCell(180)).trim().replace("",""));
			surveyAsdCc3qaVO.setC41(POIUtil.getStringCellValue(sheet.getRow(row).getCell(181)).trim().replace("",""));
			surveyAsdCc3qaVO.setC42(POIUtil.getStringCellValue(sheet.getRow(row).getCell(182)).trim().replace("",""));
			surveyAsdCc3qaVO.setC43(POIUtil.getStringCellValue(sheet.getRow(row).getCell(183)).trim().replace("",""));
			surveyAsdCc3qaVO.setC44(POIUtil.getStringCellValue(sheet.getRow(row).getCell(184)).trim().replace("",""));
			surveyAsdCc3qaVO.setC45(POIUtil.getStringCellValue(sheet.getRow(row).getCell(185)).trim().replace("",""));
			surveyAsdCc3qaVO.setC46(POIUtil.getStringCellValue(sheet.getRow(row).getCell(186)).trim().replace("",""));
			surveyAsdCc3qaVO.setC47(POIUtil.getStringCellValue(sheet.getRow(row).getCell(187)).trim().replace("",""));
			surveyAsdCc3qaVO.setC48(POIUtil.getStringCellValue(sheet.getRow(row).getCell(188)).trim().replace("",""));
			surveyAsdCc3qaVO.setC49(POIUtil.getStringCellValue(sheet.getRow(row).getCell(189)).trim().replace("",""));
			surveyAsdCc3qaVO.setC50(POIUtil.getStringCellValue(sheet.getRow(row).getCell(190)).trim().replace("",""));
			surveyAsdCc3qaVO.setScoreC(POIUtil.getStringCellValue(sheet.getRow(row).getCell(191)).trim().replace("",""));

			surveyAsdCc3qaVO.setCreateBy("excel_upload");
			surveyAsdCc3qaVO.setUpdateBy("excel_upload");	
			
		} catch(Exception e) {
			if(logger.isDebugEnabled()){
				logger.error("[Error Message] There is an Exception while mapping between cells and the object!!");
				logger.error("[Error Line] Col : " + col + ", Row : " + (row + 1) );
				logger.error("[Error Detail]");
				logger.error(e.getMessage());
				e.printStackTrace();
			}
			throw new CellReaderMapperException("There is an Exception on CellMapper!!");
		}
		return surveyAsdCc3qaVO;
	}
}
