package medical.surveyAsd.service.impl;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.poi.ss.usermodel.Sheet;

import medical.framework.file.mapping.CellReaderMapper;
import medical.framework.file.mapping.CellReaderMapperException;
import medical.framework.util.POIUtil;
import medical.surveyAsd.service.SurveyAsdPp3q1VO;

public class SurveyAsdPp3q1CellReaderMapper implements CellReaderMapper<SurveyAsdPp3q1VO>{

	protected final Log logger = LogFactory.getLog(getClass());
	
	@Override
	public SurveyAsdPp3q1VO mapCell(Sheet sheet, int col, int row) 
			throws CellReaderMapperException {
		SurveyAsdPp3q1VO surveyAsdPp3q1VO = new SurveyAsdPp3q1VO();
		try {
			surveyAsdPp3q1VO.setTargetId(POIUtil.getStringCellValue(sheet.getRow(row).getCell(0)).trim().replace("",""));
			surveyAsdPp3q1VO.setPerformCnt(POIUtil.getStringCellValue(sheet.getRow(row).getCell(2)).trim().replace("",""));
			String execDate = POIUtil.getStringCellValue(sheet.getRow(row).getCell(3)).trim().replace("","");
			surveyAsdPp3q1VO.setPp3q1ExecDate(execDate.replace("-", ""));
			surveyAsdPp3q1VO.setA1(POIUtil.getStringCellValue(sheet.getRow(row).getCell(4)).trim().replace("",""));		
			surveyAsdPp3q1VO.setA2(POIUtil.getStringCellValue(sheet.getRow(row).getCell(5)).trim().replace("",""));		
			surveyAsdPp3q1VO.setA3(POIUtil.getStringCellValue(sheet.getRow(row).getCell(6)).trim().replace("",""));		
			surveyAsdPp3q1VO.setA4(POIUtil.getStringCellValue(sheet.getRow(row).getCell(7)).trim().replace("",""));		
			surveyAsdPp3q1VO.setA5(POIUtil.getStringCellValue(sheet.getRow(row).getCell(8)).trim().replace("",""));		
			surveyAsdPp3q1VO.setA6(POIUtil.getStringCellValue(sheet.getRow(row).getCell(9)).trim().replace("",""));		
			surveyAsdPp3q1VO.setA7(POIUtil.getStringCellValue(sheet.getRow(row).getCell(10)).trim().replace("",""));		
			surveyAsdPp3q1VO.setA8(POIUtil.getStringCellValue(sheet.getRow(row).getCell(11)).trim().replace("",""));		
			surveyAsdPp3q1VO.setA9(POIUtil.getStringCellValue(sheet.getRow(row).getCell(12)).trim().replace("",""));		
			surveyAsdPp3q1VO.setA10(POIUtil.getStringCellValue(sheet.getRow(row).getCell(13)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA11(POIUtil.getStringCellValue(sheet.getRow(row).getCell(14)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA12(POIUtil.getStringCellValue(sheet.getRow(row).getCell(15)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA13(POIUtil.getStringCellValue(sheet.getRow(row).getCell(16)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA14(POIUtil.getStringCellValue(sheet.getRow(row).getCell(17)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA15(POIUtil.getStringCellValue(sheet.getRow(row).getCell(18)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA16(POIUtil.getStringCellValue(sheet.getRow(row).getCell(19)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA17(POIUtil.getStringCellValue(sheet.getRow(row).getCell(20)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA18(POIUtil.getStringCellValue(sheet.getRow(row).getCell(21)).trim().replace("",""));			
			surveyAsdPp3q1VO.setA19(POIUtil.getStringCellValue(sheet.getRow(row).getCell(22)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA20(POIUtil.getStringCellValue(sheet.getRow(row).getCell(23)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA21(POIUtil.getStringCellValue(sheet.getRow(row).getCell(24)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA22(POIUtil.getStringCellValue(sheet.getRow(row).getCell(25)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA23(POIUtil.getStringCellValue(sheet.getRow(row).getCell(26)).trim().replace("",""));	
			surveyAsdPp3q1VO.setA24(POIUtil.getStringCellValue(sheet.getRow(row).getCell(27)).trim().replace("",""));
			surveyAsdPp3q1VO.setA25(POIUtil.getStringCellValue(sheet.getRow(row).getCell(28)).trim().replace("",""));
			surveyAsdPp3q1VO.setA26(POIUtil.getStringCellValue(sheet.getRow(row).getCell(29)).trim().replace("",""));
			surveyAsdPp3q1VO.setA27(POIUtil.getStringCellValue(sheet.getRow(row).getCell(30)).trim().replace("",""));
			surveyAsdPp3q1VO.setA28(POIUtil.getStringCellValue(sheet.getRow(row).getCell(31)).trim().replace("",""));
			surveyAsdPp3q1VO.setA29(POIUtil.getStringCellValue(sheet.getRow(row).getCell(32)).trim().replace("",""));
			surveyAsdPp3q1VO.setA30(POIUtil.getStringCellValue(sheet.getRow(row).getCell(33)).trim().replace("",""));
			surveyAsdPp3q1VO.setA31(POIUtil.getStringCellValue(sheet.getRow(row).getCell(34)).trim().replace("",""));
			surveyAsdPp3q1VO.setA32(POIUtil.getStringCellValue(sheet.getRow(row).getCell(35)).trim().replace("",""));
			surveyAsdPp3q1VO.setA33(POIUtil.getStringCellValue(sheet.getRow(row).getCell(36)).trim().replace("",""));
			surveyAsdPp3q1VO.setA34(POIUtil.getStringCellValue(sheet.getRow(row).getCell(37)).trim().replace("",""));
			surveyAsdPp3q1VO.setA35(POIUtil.getStringCellValue(sheet.getRow(row).getCell(38)).trim().replace("",""));
			surveyAsdPp3q1VO.setA36(POIUtil.getStringCellValue(sheet.getRow(row).getCell(39)).trim().replace("",""));
			surveyAsdPp3q1VO.setA37(POIUtil.getStringCellValue(sheet.getRow(row).getCell(40)).trim().replace("",""));
			surveyAsdPp3q1VO.setA38(POIUtil.getStringCellValue(sheet.getRow(row).getCell(41)).trim().replace("",""));
			surveyAsdPp3q1VO.setA39(POIUtil.getStringCellValue(sheet.getRow(row).getCell(42)).trim().replace("",""));
			surveyAsdPp3q1VO.setA40(POIUtil.getStringCellValue(sheet.getRow(row).getCell(43)).trim().replace("",""));
			surveyAsdPp3q1VO.setA41(POIUtil.getStringCellValue(sheet.getRow(row).getCell(44)).trim().replace("",""));
			surveyAsdPp3q1VO.setA42(POIUtil.getStringCellValue(sheet.getRow(row).getCell(45)).trim().replace("",""));
			surveyAsdPp3q1VO.setA43(POIUtil.getStringCellValue(sheet.getRow(row).getCell(46)).trim().replace("",""));
			surveyAsdPp3q1VO.setA44(POIUtil.getStringCellValue(sheet.getRow(row).getCell(47)).trim().replace("",""));
			surveyAsdPp3q1VO.setA45(POIUtil.getStringCellValue(sheet.getRow(row).getCell(48)).trim().replace("",""));
			surveyAsdPp3q1VO.setA46(POIUtil.getStringCellValue(sheet.getRow(row).getCell(49)).trim().replace("",""));
			surveyAsdPp3q1VO.setA47(POIUtil.getStringCellValue(sheet.getRow(row).getCell(50)).trim().replace("",""));
			surveyAsdPp3q1VO.setA48(POIUtil.getStringCellValue(sheet.getRow(row).getCell(51)).trim().replace("",""));
			surveyAsdPp3q1VO.setA49(POIUtil.getStringCellValue(sheet.getRow(row).getCell(52)).trim().replace("",""));
			surveyAsdPp3q1VO.setA50(POIUtil.getStringCellValue(sheet.getRow(row).getCell(53)).trim().replace("",""));
			surveyAsdPp3q1VO.setA51(POIUtil.getStringCellValue(sheet.getRow(row).getCell(54)).trim().replace("",""));
			surveyAsdPp3q1VO.setA52(POIUtil.getStringCellValue(sheet.getRow(row).getCell(55)).trim().replace("",""));
			surveyAsdPp3q1VO.setA53(POIUtil.getStringCellValue(sheet.getRow(row).getCell(56)).trim().replace("",""));
			surveyAsdPp3q1VO.setA54(POIUtil.getStringCellValue(sheet.getRow(row).getCell(57)).trim().replace("",""));
			surveyAsdPp3q1VO.setA55(POIUtil.getStringCellValue(sheet.getRow(row).getCell(58)).trim().replace("",""));
			surveyAsdPp3q1VO.setA56(POIUtil.getStringCellValue(sheet.getRow(row).getCell(59)).trim().replace("",""));
			surveyAsdPp3q1VO.setA57(POIUtil.getStringCellValue(sheet.getRow(row).getCell(60)).trim().replace("",""));
			surveyAsdPp3q1VO.setA58(POIUtil.getStringCellValue(sheet.getRow(row).getCell(61)).trim().replace("",""));
			surveyAsdPp3q1VO.setA59(POIUtil.getStringCellValue(sheet.getRow(row).getCell(62)).trim().replace("",""));
			surveyAsdPp3q1VO.setA60(POIUtil.getStringCellValue(sheet.getRow(row).getCell(63)).trim().replace("",""));
			surveyAsdPp3q1VO.setScoreA(POIUtil.getStringCellValue(sheet.getRow(row).getCell(64)).trim().replace("",""));
			
			surveyAsdPp3q1VO.setB1(POIUtil.getStringCellValue(sheet.getRow(row).getCell(65)).trim().replace("",""));
			surveyAsdPp3q1VO.setB2(POIUtil.getStringCellValue(sheet.getRow(row).getCell(66)).trim().replace("",""));
			surveyAsdPp3q1VO.setB3(POIUtil.getStringCellValue(sheet.getRow(row).getCell(67)).trim().replace("",""));
			surveyAsdPp3q1VO.setB4(POIUtil.getStringCellValue(sheet.getRow(row).getCell(68)).trim().replace("",""));
			surveyAsdPp3q1VO.setB5(POIUtil.getStringCellValue(sheet.getRow(row).getCell(69)).trim().replace("",""));
			surveyAsdPp3q1VO.setB6(POIUtil.getStringCellValue(sheet.getRow(row).getCell(70)).trim().replace("",""));
			surveyAsdPp3q1VO.setB7(POIUtil.getStringCellValue(sheet.getRow(row).getCell(71)).trim().replace("",""));
			surveyAsdPp3q1VO.setB8(POIUtil.getStringCellValue(sheet.getRow(row).getCell(72)).trim().replace("",""));
			surveyAsdPp3q1VO.setB9(POIUtil.getStringCellValue(sheet.getRow(row).getCell(73)).trim().replace("",""));
			surveyAsdPp3q1VO.setB10(POIUtil.getStringCellValue(sheet.getRow(row).getCell(74)).trim().replace("",""));
			surveyAsdPp3q1VO.setB11(POIUtil.getStringCellValue(sheet.getRow(row).getCell(75)).trim().replace("",""));
			surveyAsdPp3q1VO.setB12(POIUtil.getStringCellValue(sheet.getRow(row).getCell(76)).trim().replace("",""));
			surveyAsdPp3q1VO.setB13(POIUtil.getStringCellValue(sheet.getRow(row).getCell(77)).trim().replace("",""));
			surveyAsdPp3q1VO.setB14(POIUtil.getStringCellValue(sheet.getRow(row).getCell(78)).trim().replace("",""));
			surveyAsdPp3q1VO.setB15(POIUtil.getStringCellValue(sheet.getRow(row).getCell(79)).trim().replace("",""));
			surveyAsdPp3q1VO.setB16(POIUtil.getStringCellValue(sheet.getRow(row).getCell(80)).trim().replace("",""));
			surveyAsdPp3q1VO.setB17(POIUtil.getStringCellValue(sheet.getRow(row).getCell(81)).trim().replace("",""));
			surveyAsdPp3q1VO.setB18(POIUtil.getStringCellValue(sheet.getRow(row).getCell(82)).trim().replace("",""));
			surveyAsdPp3q1VO.setB19(POIUtil.getStringCellValue(sheet.getRow(row).getCell(83)).trim().replace("",""));
			surveyAsdPp3q1VO.setB20(POIUtil.getStringCellValue(sheet.getRow(row).getCell(84)).trim().replace("",""));
			surveyAsdPp3q1VO.setB21(POIUtil.getStringCellValue(sheet.getRow(row).getCell(85)).trim().replace("",""));
			surveyAsdPp3q1VO.setB22(POIUtil.getStringCellValue(sheet.getRow(row).getCell(86)).trim().replace("",""));
			surveyAsdPp3q1VO.setB23(POIUtil.getStringCellValue(sheet.getRow(row).getCell(87)).trim().replace("",""));
			surveyAsdPp3q1VO.setB24(POIUtil.getStringCellValue(sheet.getRow(row).getCell(88)).trim().replace("",""));
			surveyAsdPp3q1VO.setB25(POIUtil.getStringCellValue(sheet.getRow(row).getCell(89)).trim().replace("",""));
			surveyAsdPp3q1VO.setB26(POIUtil.getStringCellValue(sheet.getRow(row).getCell(90)).trim().replace("",""));
			surveyAsdPp3q1VO.setB27(POIUtil.getStringCellValue(sheet.getRow(row).getCell(91)).trim().replace("",""));
			surveyAsdPp3q1VO.setB28(POIUtil.getStringCellValue(sheet.getRow(row).getCell(92)).trim().replace("",""));
			surveyAsdPp3q1VO.setB29(POIUtil.getStringCellValue(sheet.getRow(row).getCell(93)).trim().replace("",""));
			surveyAsdPp3q1VO.setB30(POIUtil.getStringCellValue(sheet.getRow(row).getCell(94)).trim().replace("",""));
			surveyAsdPp3q1VO.setB31(POIUtil.getStringCellValue(sheet.getRow(row).getCell(95)).trim().replace("",""));
			surveyAsdPp3q1VO.setB32(POIUtil.getStringCellValue(sheet.getRow(row).getCell(96)).trim().replace("",""));
			surveyAsdPp3q1VO.setB33(POIUtil.getStringCellValue(sheet.getRow(row).getCell(97)).trim().replace("",""));
			surveyAsdPp3q1VO.setB34(POIUtil.getStringCellValue(sheet.getRow(row).getCell(98)).trim().replace("",""));
			surveyAsdPp3q1VO.setB35(POIUtil.getStringCellValue(sheet.getRow(row).getCell(99)).trim().replace("",""));
			surveyAsdPp3q1VO.setB36(POIUtil.getStringCellValue(sheet.getRow(row).getCell(100)).trim().replace("",""));
			surveyAsdPp3q1VO.setB37(POIUtil.getStringCellValue(sheet.getRow(row).getCell(101)).trim().replace("",""));
			surveyAsdPp3q1VO.setB38(POIUtil.getStringCellValue(sheet.getRow(row).getCell(102)).trim().replace("",""));
			surveyAsdPp3q1VO.setB39(POIUtil.getStringCellValue(sheet.getRow(row).getCell(103)).trim().replace("",""));
			surveyAsdPp3q1VO.setB40(POIUtil.getStringCellValue(sheet.getRow(row).getCell(104)).trim().replace("",""));
			surveyAsdPp3q1VO.setB41(POIUtil.getStringCellValue(sheet.getRow(row).getCell(105)).trim().replace("",""));
			surveyAsdPp3q1VO.setB42(POIUtil.getStringCellValue(sheet.getRow(row).getCell(106)).trim().replace("",""));
			surveyAsdPp3q1VO.setB43(POIUtil.getStringCellValue(sheet.getRow(row).getCell(107)).trim().replace("",""));
			surveyAsdPp3q1VO.setB44(POIUtil.getStringCellValue(sheet.getRow(row).getCell(108)).trim().replace("",""));
			surveyAsdPp3q1VO.setB45(POIUtil.getStringCellValue(sheet.getRow(row).getCell(109)).trim().replace("",""));
			surveyAsdPp3q1VO.setB46(POIUtil.getStringCellValue(sheet.getRow(row).getCell(110)).trim().replace("",""));
			surveyAsdPp3q1VO.setB47(POIUtil.getStringCellValue(sheet.getRow(row).getCell(111)).trim().replace("",""));
			surveyAsdPp3q1VO.setB48(POIUtil.getStringCellValue(sheet.getRow(row).getCell(112)).trim().replace("",""));
			surveyAsdPp3q1VO.setB49(POIUtil.getStringCellValue(sheet.getRow(row).getCell(113)).trim().replace("",""));
			surveyAsdPp3q1VO.setB50(POIUtil.getStringCellValue(sheet.getRow(row).getCell(114)).trim().replace("",""));
			surveyAsdPp3q1VO.setB51(POIUtil.getStringCellValue(sheet.getRow(row).getCell(115)).trim().replace("",""));
			surveyAsdPp3q1VO.setB52(POIUtil.getStringCellValue(sheet.getRow(row).getCell(116)).trim().replace("",""));
			surveyAsdPp3q1VO.setB53(POIUtil.getStringCellValue(sheet.getRow(row).getCell(117)).trim().replace("",""));
			surveyAsdPp3q1VO.setB54(POIUtil.getStringCellValue(sheet.getRow(row).getCell(118)).trim().replace("",""));
			surveyAsdPp3q1VO.setB55(POIUtil.getStringCellValue(sheet.getRow(row).getCell(119)).trim().replace("",""));
			surveyAsdPp3q1VO.setB56(POIUtil.getStringCellValue(sheet.getRow(row).getCell(120)).trim().replace("",""));
			surveyAsdPp3q1VO.setB57(POIUtil.getStringCellValue(sheet.getRow(row).getCell(121)).trim().replace("",""));
			surveyAsdPp3q1VO.setB58(POIUtil.getStringCellValue(sheet.getRow(row).getCell(122)).trim().replace("",""));
			surveyAsdPp3q1VO.setB59(POIUtil.getStringCellValue(sheet.getRow(row).getCell(123)).trim().replace("",""));
			surveyAsdPp3q1VO.setB60(POIUtil.getStringCellValue(sheet.getRow(row).getCell(124)).trim().replace("",""));
			surveyAsdPp3q1VO.setB61(POIUtil.getStringCellValue(sheet.getRow(row).getCell(125)).trim().replace("",""));
			surveyAsdPp3q1VO.setB62(POIUtil.getStringCellValue(sheet.getRow(row).getCell(126)).trim().replace("",""));
			surveyAsdPp3q1VO.setB63(POIUtil.getStringCellValue(sheet.getRow(row).getCell(127)).trim().replace("",""));
			surveyAsdPp3q1VO.setB64(POIUtil.getStringCellValue(sheet.getRow(row).getCell(128)).trim().replace("",""));
			surveyAsdPp3q1VO.setB65(POIUtil.getStringCellValue(sheet.getRow(row).getCell(129)).trim().replace("",""));
			surveyAsdPp3q1VO.setB66(POIUtil.getStringCellValue(sheet.getRow(row).getCell(130)).trim().replace("",""));
			surveyAsdPp3q1VO.setB67(POIUtil.getStringCellValue(sheet.getRow(row).getCell(131)).trim().replace("",""));
			surveyAsdPp3q1VO.setB68(POIUtil.getStringCellValue(sheet.getRow(row).getCell(132)).trim().replace("",""));
			surveyAsdPp3q1VO.setB69(POIUtil.getStringCellValue(sheet.getRow(row).getCell(133)).trim().replace("",""));
			surveyAsdPp3q1VO.setB70(POIUtil.getStringCellValue(sheet.getRow(row).getCell(134)).trim().replace("",""));
			surveyAsdPp3q1VO.setB71(POIUtil.getStringCellValue(sheet.getRow(row).getCell(135)).trim().replace("",""));
			surveyAsdPp3q1VO.setB72(POIUtil.getStringCellValue(sheet.getRow(row).getCell(136)).trim().replace("",""));
			surveyAsdPp3q1VO.setB73(POIUtil.getStringCellValue(sheet.getRow(row).getCell(137)).trim().replace("",""));
			surveyAsdPp3q1VO.setB74(POIUtil.getStringCellValue(sheet.getRow(row).getCell(138)).trim().replace("",""));
			surveyAsdPp3q1VO.setB75(POIUtil.getStringCellValue(sheet.getRow(row).getCell(139)).trim().replace("",""));
			surveyAsdPp3q1VO.setScoreB(POIUtil.getStringCellValue(sheet.getRow(row).getCell(140)).trim().replace("",""));

			surveyAsdPp3q1VO.setC1(POIUtil.getStringCellValue(sheet.getRow(row).getCell(141)).trim().replace("",""));
			surveyAsdPp3q1VO.setC2(POIUtil.getStringCellValue(sheet.getRow(row).getCell(142)).trim().replace("",""));
			surveyAsdPp3q1VO.setC3(POIUtil.getStringCellValue(sheet.getRow(row).getCell(143)).trim().replace("",""));
			surveyAsdPp3q1VO.setC4(POIUtil.getStringCellValue(sheet.getRow(row).getCell(144)).trim().replace("",""));
			surveyAsdPp3q1VO.setC5(POIUtil.getStringCellValue(sheet.getRow(row).getCell(145)).trim().replace("",""));
			surveyAsdPp3q1VO.setC6(POIUtil.getStringCellValue(sheet.getRow(row).getCell(146)).trim().replace("",""));
			surveyAsdPp3q1VO.setC7(POIUtil.getStringCellValue(sheet.getRow(row).getCell(147)).trim().replace("",""));
			surveyAsdPp3q1VO.setC8(POIUtil.getStringCellValue(sheet.getRow(row).getCell(148)).trim().replace("",""));
			surveyAsdPp3q1VO.setC9(POIUtil.getStringCellValue(sheet.getRow(row).getCell(149)).trim().replace("",""));
			surveyAsdPp3q1VO.setC10(POIUtil.getStringCellValue(sheet.getRow(row).getCell(150)).trim().replace("",""));
			surveyAsdPp3q1VO.setC11(POIUtil.getStringCellValue(sheet.getRow(row).getCell(151)).trim().replace("",""));
			surveyAsdPp3q1VO.setC12(POIUtil.getStringCellValue(sheet.getRow(row).getCell(152)).trim().replace("",""));
			surveyAsdPp3q1VO.setC13(POIUtil.getStringCellValue(sheet.getRow(row).getCell(153)).trim().replace("",""));
			surveyAsdPp3q1VO.setC14(POIUtil.getStringCellValue(sheet.getRow(row).getCell(154)).trim().replace("",""));
			surveyAsdPp3q1VO.setC15(POIUtil.getStringCellValue(sheet.getRow(row).getCell(155)).trim().replace("",""));
			surveyAsdPp3q1VO.setC16(POIUtil.getStringCellValue(sheet.getRow(row).getCell(156)).trim().replace("",""));
			surveyAsdPp3q1VO.setC17(POIUtil.getStringCellValue(sheet.getRow(row).getCell(157)).trim().replace("",""));
			surveyAsdPp3q1VO.setC18(POIUtil.getStringCellValue(sheet.getRow(row).getCell(158)).trim().replace("",""));
			surveyAsdPp3q1VO.setC19(POIUtil.getStringCellValue(sheet.getRow(row).getCell(159)).trim().replace("",""));
			surveyAsdPp3q1VO.setC20(POIUtil.getStringCellValue(sheet.getRow(row).getCell(160)).trim().replace("",""));
			surveyAsdPp3q1VO.setC21(POIUtil.getStringCellValue(sheet.getRow(row).getCell(161)).trim().replace("",""));
			surveyAsdPp3q1VO.setC22(POIUtil.getStringCellValue(sheet.getRow(row).getCell(162)).trim().replace("",""));
			surveyAsdPp3q1VO.setC23(POIUtil.getStringCellValue(sheet.getRow(row).getCell(163)).trim().replace("",""));
			surveyAsdPp3q1VO.setC24(POIUtil.getStringCellValue(sheet.getRow(row).getCell(164)).trim().replace("",""));
			surveyAsdPp3q1VO.setC25(POIUtil.getStringCellValue(sheet.getRow(row).getCell(165)).trim().replace("",""));
			surveyAsdPp3q1VO.setC26(POIUtil.getStringCellValue(sheet.getRow(row).getCell(166)).trim().replace("",""));
			surveyAsdPp3q1VO.setC27(POIUtil.getStringCellValue(sheet.getRow(row).getCell(167)).trim().replace("",""));
			surveyAsdPp3q1VO.setC28(POIUtil.getStringCellValue(sheet.getRow(row).getCell(168)).trim().replace("",""));
			surveyAsdPp3q1VO.setC29(POIUtil.getStringCellValue(sheet.getRow(row).getCell(169)).trim().replace("",""));
			surveyAsdPp3q1VO.setC30(POIUtil.getStringCellValue(sheet.getRow(row).getCell(170)).trim().replace("",""));
			surveyAsdPp3q1VO.setC31(POIUtil.getStringCellValue(sheet.getRow(row).getCell(171)).trim().replace("",""));
			surveyAsdPp3q1VO.setC32(POIUtil.getStringCellValue(sheet.getRow(row).getCell(172)).trim().replace("",""));
			surveyAsdPp3q1VO.setC33(POIUtil.getStringCellValue(sheet.getRow(row).getCell(173)).trim().replace("",""));
			surveyAsdPp3q1VO.setC34(POIUtil.getStringCellValue(sheet.getRow(row).getCell(174)).trim().replace("",""));
			surveyAsdPp3q1VO.setC35(POIUtil.getStringCellValue(sheet.getRow(row).getCell(175)).trim().replace("",""));
			surveyAsdPp3q1VO.setC36(POIUtil.getStringCellValue(sheet.getRow(row).getCell(176)).trim().replace("",""));
			surveyAsdPp3q1VO.setC37(POIUtil.getStringCellValue(sheet.getRow(row).getCell(177)).trim().replace("",""));
			surveyAsdPp3q1VO.setC38(POIUtil.getStringCellValue(sheet.getRow(row).getCell(178)).trim().replace("",""));
			surveyAsdPp3q1VO.setC39(POIUtil.getStringCellValue(sheet.getRow(row).getCell(179)).trim().replace("",""));
			surveyAsdPp3q1VO.setC40(POIUtil.getStringCellValue(sheet.getRow(row).getCell(180)).trim().replace("",""));
			surveyAsdPp3q1VO.setC41(POIUtil.getStringCellValue(sheet.getRow(row).getCell(181)).trim().replace("",""));
			surveyAsdPp3q1VO.setC42(POIUtil.getStringCellValue(sheet.getRow(row).getCell(182)).trim().replace("",""));
			surveyAsdPp3q1VO.setC43(POIUtil.getStringCellValue(sheet.getRow(row).getCell(183)).trim().replace("",""));
			surveyAsdPp3q1VO.setC44(POIUtil.getStringCellValue(sheet.getRow(row).getCell(184)).trim().replace("",""));
			surveyAsdPp3q1VO.setC45(POIUtil.getStringCellValue(sheet.getRow(row).getCell(185)).trim().replace("",""));
			surveyAsdPp3q1VO.setC46(POIUtil.getStringCellValue(sheet.getRow(row).getCell(186)).trim().replace("",""));
			surveyAsdPp3q1VO.setC47(POIUtil.getStringCellValue(sheet.getRow(row).getCell(187)).trim().replace("",""));
			surveyAsdPp3q1VO.setC48(POIUtil.getStringCellValue(sheet.getRow(row).getCell(188)).trim().replace("",""));
			surveyAsdPp3q1VO.setC49(POIUtil.getStringCellValue(sheet.getRow(row).getCell(189)).trim().replace("",""));
			surveyAsdPp3q1VO.setC50(POIUtil.getStringCellValue(sheet.getRow(row).getCell(190)).trim().replace("",""));
			surveyAsdPp3q1VO.setScoreC(POIUtil.getStringCellValue(sheet.getRow(row).getCell(191)).trim().replace("",""));

			surveyAsdPp3q1VO.setCreateBy("excel_upload");
			surveyAsdPp3q1VO.setUpdateBy("excel_upload");	
			
		} catch(Exception e) {
			if(logger.isDebugEnabled()){
				logger.error("[Error Message] There is an Exception while mapping between cells and the object!!");
				logger.error("[Error Line] Col : " + col + ", Row : " + (row + 1) );
				logger.error("[Error Detail]");
				logger.error(e.getMessage());
				e.printStackTrace();
			}
			throw new CellReaderMapperException("There is an Exception on CellMapper!!");
		}
		return surveyAsdPp3q1VO;
	}
}
