package medical.neuropsy.service.impl;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.util.CellRangeAddress;

import medical.framework.file.mapping.CellWriterMapper;
import medical.neuropsy.service.NeuropsyS1VO;

public class NeuropsyS1WriterMapper implements CellWriterMapper<NeuropsyS1VO>{
	@Override
	public void mapHeader(Row row, NeuropsyS1VO vo) {
		Cell cell = null;
		int i = 0;
		
		int rowNum = row.getRowNum();
		
		if(rowNum==0) {
		cell = row.createCell(i++);
		cell.setCellValue("연구번호");

		cell = row.createCell(i++);
		cell.setCellValue("성별");

		cell = row.createCell(i++);
		cell.setCellValue("프로토콜");
		
		cell = row.createCell(i++);
		cell.setCellValue("차수");

		cell = row.createCell(i++);
		cell.setCellValue("나이");

		cell = row.createCell(i++);
		cell.setCellValue("K-SADS\r실시일");	
		
		cell = row.createCell(i++);
		cell.setCellValue("Tic\rsubtype");	
		
		cell = row.createCell(i++);
		cell.setCellValue("지능검사\r실시날짜");
		
		cell = row.createCell(i++);
		cell.setCellValue("FSIQ");
		
		cell = row.createCell(i++);
		cell.setCellValue("KEDI-WAIS");

		cell = row.createCell(17);
		cell.setCellValue("K-WISC-IV");
		
		cell = row.createCell(37);
		cell.setCellValue("K-WAIS-IV");
		
		cell = row.createCell(57);
		cell.setCellValue("K-SADS");
		
		cell = row.createCell(131);
		cell.setCellValue("틱장애\r부록");
		
		cell = row.createCell(190);
		}
		if(rowNum==1) {
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell.setCellValue("원점수");
			cell = row.createCell(10);
			cell = row.createCell(11);
			cell = row.createCell(12);
			cell = row.createCell(13);
			cell.setCellValue("환산점수");
			cell = row.createCell(14);
			cell = row.createCell(15);
			cell = row.createCell(16);
			cell = row.createCell(17);
			cell.setCellValue("원점수");
			cell = row.createCell(18);
			cell = row.createCell(19);
			cell = row.createCell(20);
			cell = row.createCell(21);
			cell = row.createCell(22);
			cell = row.createCell(23);
			cell = row.createCell(24);
			cell = row.createCell(25);
			cell = row.createCell(26);
			cell = row.createCell(27);
			cell.setCellValue("환산점수");
			cell = row.createCell(28);
			cell = row.createCell(29);
			cell = row.createCell(30);
			cell = row.createCell(31);
			cell = row.createCell(32);
			cell = row.createCell(33);
			cell = row.createCell(34);
			cell = row.createCell(35);
			cell = row.createCell(36);
			cell = row.createCell(37);
			cell.setCellValue("원점수");
			cell = row.createCell(38);
			cell = row.createCell(39);
			cell = row.createCell(40);
			cell = row.createCell(41);
			cell = row.createCell(42);
			cell = row.createCell(43);
			cell = row.createCell(44);
			cell = row.createCell(45);
			cell = row.createCell(46);
			cell = row.createCell(47);
			cell.setCellValue("환산점수");
			cell = row.createCell(48);
			cell = row.createCell(49);
			cell = row.createCell(50);
			cell = row.createCell(51);
			cell = row.createCell(52);
			cell = row.createCell(53);
			cell = row.createCell(54);
			cell = row.createCell(55);
			cell = row.createCell(56);
			cell = row.createCell(57);
			cell.setCellValue("선별-우울");
			cell = row.createCell(58);
			cell = row.createCell(59);
			cell = row.createCell(60);
			cell = row.createCell(61);
			cell = row.createCell(62);
			cell = row.createCell(63);
			cell = row.createCell(64);
			cell = row.createCell(65);
			cell.setCellValue("선별-조증");
			cell = row.createCell(66);
			cell = row.createCell(67);
			cell = row.createCell(68);
			cell = row.createCell(69);
			cell.setCellValue("선별-정신증");
			cell = row.createCell(70);
			cell = row.createCell(71);
			cell.setCellValue("선별-공황장애");
			cell = row.createCell(72);
			cell.setCellValue("선별-분리불안장애");
			cell = row.createCell(73);
			cell = row.createCell(74);
			cell = row.createCell(75);
			cell = row.createCell(76);
			cell = row.createCell(77);
			cell.setCellValue("선별-회피성장애");
			cell = row.createCell(78);
			cell = row.createCell(79);
			cell.setCellValue("선별-광장공포");
			cell = row.createCell(80);
			cell = row.createCell(81);
			cell.setCellValue("선별-과불안");
			cell = row.createCell(82);
			cell = row.createCell(83);
			cell = row.createCell(84);
			cell = row.createCell(85);
			cell.setCellValue("선별-강박증");
			cell = row.createCell(86);
			cell = row.createCell(87);
			cell.setCellValue("선별-유뇨증, 유분증");
			cell = row.createCell(88);
			cell = row.createCell(89);
			cell = row.createCell(90);
			cell = row.createCell(91);
			cell = row.createCell(92);
			cell = row.createCell(93);
			cell.setCellValue("살찌는거\r두려움");
			cell = row.createCell(94);
			cell.setCellValue("저체중");
			cell = row.createCell(95);
			cell.setCellValue("체중감량");
			cell = row.createCell(96);
			cell.setCellValue("폭식");
			cell = row.createCell(97);
			cell.setCellValue("선별-ADHD");
			cell = row.createCell(98);
			cell = row.createCell(99);
			cell = row.createCell(100);
			cell = row.createCell(101);
			cell.setCellValue("선별-ODD");
			cell = row.createCell(102);
			cell = row.createCell(103);
			cell = row.createCell(104);
			cell.setCellValue("선별-CD");
			cell = row.createCell(105);
			cell = row.createCell(106);
			cell = row.createCell(107);
			cell = row.createCell(108);
			cell = row.createCell(109);
			cell.setCellValue("선별-틱");
			cell = row.createCell(110);
			cell = row.createCell(111);
			cell.setCellValue("GAS");
			cell = row.createCell(112);
			cell.setCellValue("ADHD 요건");
			cell = row.createCell(113);
			cell = row.createCell(114);
			cell = row.createCell(115);
			cell = row.createCell(116);
			cell = row.createCell(117);
			cell = row.createCell(118);
			cell = row.createCell(119);
			cell = row.createCell(120);
			cell = row.createCell(121);
			cell = row.createCell(122);
			cell = row.createCell(123);
			cell = row.createCell(124);
			cell = row.createCell(125);
			cell = row.createCell(126);
			cell = row.createCell(127);
			cell = row.createCell(128);
			cell = row.createCell(129);
			cell = row.createCell(130);
			cell = row.createCell(131);
			cell.setCellValue("단순운동틱");
			cell = row.createCell(132);
			cell = row.createCell(133);
			cell = row.createCell(134);
			cell = row.createCell(135);
			cell = row.createCell(136);
			cell = row.createCell(137);
			cell = row.createCell(138);
			cell = row.createCell(139);
			cell = row.createCell(140);
			cell = row.createCell(141);
			cell = row.createCell(142);
			cell = row.createCell(143);
			cell = row.createCell(144);
			cell = row.createCell(145);
			cell = row.createCell(146);
			cell = row.createCell(147);
			cell.setCellValue("복합운동틱");
			cell = row.createCell(148);
			cell = row.createCell(149);
			cell = row.createCell(150);
			cell = row.createCell(151);
			cell = row.createCell(152);
			cell = row.createCell(153);
			cell = row.createCell(154);
			cell = row.createCell(155);
			cell = row.createCell(156);
			cell = row.createCell(157);
			cell.setCellValue("단순음성틱");
			cell = row.createCell(158);
			cell = row.createCell(159);
			cell = row.createCell(160);
			cell = row.createCell(161);
			cell = row.createCell(162);
			cell = row.createCell(163);
			cell.setCellValue("복합음성틱");
			cell = row.createCell(164);
			cell = row.createCell(165);
			cell = row.createCell(166);
			cell = row.createCell(167);
			cell = row.createCell(168);
			cell = row.createCell(169);
			cell = row.createCell(170);
			cell = row.createCell(171);
			cell = row.createCell(172);
			cell = row.createCell(173);
			cell = row.createCell(174);
			cell = row.createCell(175);
			cell = row.createCell(176);
			cell = row.createCell(177);
			cell = row.createCell(178);
			cell = row.createCell(179);
			cell.setCellValue("뚜렛장애의 진단기준");
			cell = row.createCell(180);
			cell = row.createCell(181);
			cell = row.createCell(182);
			cell = row.createCell(183);
			cell.setCellValue("만성틱의 진단기준");
			cell = row.createCell(184);
			cell = row.createCell(185);
			cell = row.createCell(186);
			cell = row.createCell(187);
			cell.setCellValue("일과성틱의 진단기준");
			cell = row.createCell(188);
			cell = row.createCell(189);
			cell = row.createCell(190);
		}
		if(rowNum==2) {
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(i++);
			cell = row.createCell(9);
			cell.setCellValue("어휘");
			cell = row.createCell(10);
			cell.setCellValue("산수");
			cell = row.createCell(11);
			cell.setCellValue("차례");
			cell = row.createCell(12);
			cell.setCellValue("토막");
			cell = row.createCell(13);
			cell.setCellValue("어휘");
			cell = row.createCell(14);
			cell.setCellValue("산수");
			cell = row.createCell(15);
			cell.setCellValue("차례");
			cell = row.createCell(16);
			cell.setCellValue("토막");
			cell = row.createCell(17);
			cell.setCellValue("공통성");
			cell = row.createCell(18);
			cell.setCellValue("어휘");
			cell = row.createCell(19);
			cell.setCellValue("이해");
			cell = row.createCell(20);
			cell.setCellValue("토막");
			cell = row.createCell(21);
			cell.setCellValue("공통그림");
			cell = row.createCell(22);
			cell.setCellValue("행렬");
			cell = row.createCell(23);
			cell.setCellValue("숫자");
			cell = row.createCell(24);
			cell.setCellValue("순차연결");
			cell = row.createCell(25);
			cell.setCellValue("기호");
			cell = row.createCell(26);
			cell.setCellValue("동형");
			cell = row.createCell(27);
			cell.setCellValue("공통성");
			cell = row.createCell(28);
			cell.setCellValue("어휘");
			cell = row.createCell(29);
			cell.setCellValue("이해");
			cell = row.createCell(30);
			cell.setCellValue("토막");
			cell = row.createCell(31);
			cell.setCellValue("공통그림");
			cell = row.createCell(32);
			cell.setCellValue("행렬");
			cell = row.createCell(33);
			cell.setCellValue("숫자");
			cell = row.createCell(34);
			cell.setCellValue("순차연결");
			cell = row.createCell(35);
			cell.setCellValue("기호");
			cell = row.createCell(36);
			cell.setCellValue("동형");
			cell = row.createCell(37);
			cell.setCellValue("공통성\nSI");
			cell = row.createCell(38);
			cell.setCellValue("어휘\nVC");
			cell = row.createCell(39);
			cell.setCellValue("상식\nIN");
			cell = row.createCell(40);
			cell.setCellValue("토막짜기\nBD");
			cell = row.createCell(41);
			cell.setCellValue("행렬추론\nMR");
			cell = row.createCell(42);
			cell.setCellValue("퍼즐\nVP");
			cell = row.createCell(43);
			cell.setCellValue("숫자\nDS");
			cell = row.createCell(44);
			cell.setCellValue("산수\nAR");
			cell = row.createCell(45);
			cell.setCellValue("동형찾기\nSS");
			cell = row.createCell(46);
			cell.setCellValue("기호쓰기\nCD");
			cell = row.createCell(47);
			cell.setCellValue("공통성\nSI");
			cell = row.createCell(48);
			cell.setCellValue("어휘\nVC");
			cell = row.createCell(49);
			cell.setCellValue("상식\nIN");
			cell = row.createCell(50);
			cell.setCellValue("토막짜기\nBD");
			cell = row.createCell(51);
			cell.setCellValue("행렬추론\nMR");
			cell = row.createCell(52);
			cell.setCellValue("퍼즐\nVP");
			cell = row.createCell(53);
			cell.setCellValue("숫자\nDS");
			cell = row.createCell(54);
			cell.setCellValue("산수\nAR");
			cell = row.createCell(55);
			cell.setCellValue("동형찾기\nSS");
			cell = row.createCell(56);
			cell.setCellValue("기호쓰기\nCD");
			cell = row.createCell(57);
			cell.setCellValue("우울한기분");
			cell = row.createCell(58);
			cell.setCellValue("과민성 및 분노");
			cell = row.createCell(59);
			cell.setCellValue("동기저하");
			cell = row.createCell(60);
			cell.setCellValue("죽음에 대한 사고");
			cell = row.createCell(61);
			cell.setCellValue("자살사고");
			cell = row.createCell(62);
			cell.setCellValue("자살행위-심각도");
			cell = row.createCell(63);
			cell.setCellValue("자살행위-치명도");
			cell = row.createCell(64);
			cell.setCellValue("자해");
			cell = row.createCell(65);
			cell.setCellValue("고양감");
			cell = row.createCell(66);
			cell.setCellValue("수면욕구감소");
			cell = row.createCell(67);
			cell.setCellValue("목표지향활동");
			cell = row.createCell(68);
			cell.setCellValue("질주사고");
			cell = row.createCell(69);
			cell.setCellValue("환각");
			cell = row.createCell(70);
			cell.setCellValue("망상");
			cell = row.createCell(71);
			cell.setCellValue("공황발작");
			cell = row.createCell(72);
			cell.setCellValue("분리사건두려움");
			cell = row.createCell(73);
			cell.setCellValue("애착대상 두려움");
			cell = row.createCell(74);
			cell.setCellValue("학교거부");
			cell = row.createCell(75);
			cell.setCellValue("혼자자기 두려움");
			cell = row.createCell(76);
			cell.setCellValue("집에혼자 두려움");
			cell = row.createCell(77);
			cell.setCellValue("위축");
			cell = row.createCell(78);
			cell.setCellValue("사회적상황 두려움");
			cell = row.createCell(79);
			cell.setCellValue("고통");
			cell = row.createCell(80);
			cell.setCellValue("회피");
			cell = row.createCell(81);
			cell.setCellValue("미래에 대한 걱정");
			cell = row.createCell(82);
			cell.setCellValue("신체 불평");
			cell = row.createCell(83);
			cell.setCellValue("현저한 자의식");
			cell = row.createCell(84);
			cell.setCellValue("현저한긴장감");
			cell = row.createCell(85);
			cell.setCellValue("강박행동");
			cell = row.createCell(86);
			cell.setCellValue("강박사고");
			cell = row.createCell(87);
			cell.setCellValue("소변 저녁");
			cell = row.createCell(88);
			cell.setCellValue("소변 낮");
			cell = row.createCell(89);
			cell.setCellValue("소변 합계");
			cell = row.createCell(90);
			cell.setCellValue("대변 저녁");
			cell = row.createCell(91);
			cell.setCellValue("대변 낮");
			cell = row.createCell(92);
			cell.setCellValue("대변 합계");
			cell = row.createCell(93);
			cell = row.createCell(94);
			cell = row.createCell(95);
			cell = row.createCell(96);
			cell = row.createCell(97);
			cell.setCellValue("지속어려움");
			cell = row.createCell(98);
			cell.setCellValue("쉽게 산만");

			cell = row.createCell(99);
			cell.setCellValue("앉아있기 어려움");
			cell = row.createCell(100);
			cell.setCellValue("충동성");
			cell = row.createCell(101);
			cell.setCellValue("욱하고 화내기");
			cell = row.createCell(102);
			cell.setCellValue("어른과 말다툼");
			cell = row.createCell(103);
			cell.setCellValue("규칙따르지않음");
			cell = row.createCell(104);
			cell.setCellValue("거짓말");
			cell = row.createCell(105);
			cell.setCellValue("무단결석");
			cell = row.createCell(106);
			cell.setCellValue("신체적싸움");
			cell = row.createCell(107);
			cell.setCellValue("괴롭힘");
			cell = row.createCell(108);
			cell.setCellValue("도둑질");
			cell = row.createCell(109);
			cell.setCellValue("운동틱");
			cell = row.createCell(110);
			cell.setCellValue("음성틱");
			cell = row.createCell(111);
			cell = row.createCell(112);
			cell.setCellValue("1. 부주의한 실수");
			cell = row.createCell(113);
			cell.setCellValue("2. 경청X");
			cell = row.createCell(114);
			cell.setCellValue("3. 지시따르기 어려움");
			cell = row.createCell(115);
			cell.setCellValue("4. 과제 정리어려움");
			cell = row.createCell(116);
			cell.setCellValue("5. 주의력요하는 과제회피");
			cell = row.createCell(117);
			cell.setCellValue("6 물건을 분실");
			cell = row.createCell(118);
			cell.setCellValue("7. 일상활동 건망증");
			cell = row.createCell(119);
			cell.setCellValue("8. 안절부절못함");
			cell = row.createCell(120);
			cell.setCellValue("9. 지나치게 뛰거나 기어오름");
			cell = row.createCell(121);
			cell.setCellValue("10. 끊임없이 활동");
			cell = row.createCell(122);
			cell.setCellValue("11. 조용하게 노느데 어려움");
			cell = row.createCell(123);
			cell.setCellValue("12. 불쑥 대답");
			cell = row.createCell(124);
			cell.setCellValue("13. 순서 기다리는데 어려움");
			cell = row.createCell(125);
			cell.setCellValue("14. 방해, 끼어들기");
			cell = row.createCell(126);
			cell.setCellValue("15. 활동 이것저것바꿈");
			cell = row.createCell(127);
			cell.setCellValue("16. 지나치게 많이 말함");
			cell = row.createCell(128);
			cell.setCellValue("17. 신체적으로 위험한 활동");
			cell = row.createCell(129);
			cell.setCellValue("진단");
			cell = row.createCell(130);
			cell.setCellValue("기타진단");
			cell = row.createCell(131);
			cell.setCellValue("1.요약CE");
			cell = row.createCell(132);
			cell.setCellValue("1.요약MSP");
			cell = row.createCell(133);
			cell.setCellValue("2.요약CE");
			cell = row.createCell(134);
			cell.setCellValue("2.요약MSP");
			cell = row.createCell(135);
			cell.setCellValue("3.요약CE");
			cell = row.createCell(136);
			cell.setCellValue("3.요약MSP");
			cell = row.createCell(137);
			cell.setCellValue("4.요약CE");
			cell = row.createCell(138);
			cell.setCellValue("4.요약MSP");
			cell = row.createCell(139);
			cell.setCellValue("5.요약CE");
			cell = row.createCell(140);
			cell.setCellValue("5.요약MSP");
			cell = row.createCell(141);
			cell.setCellValue("6.요약CE");
			cell = row.createCell(142);
			cell.setCellValue("6.요약MSP");
			cell = row.createCell(143);
			cell.setCellValue("7.요약CE");
			cell = row.createCell(144);
			cell.setCellValue("7요약MSP");
			cell = row.createCell(145);
			cell.setCellValue("8.요약CE");
			cell = row.createCell(146);
			cell.setCellValue("8.요약MSP");
			cell = row.createCell(147);
			cell.setCellValue("1.요약CE");
			cell = row.createCell(148);
			cell.setCellValue("1.요약MSP");
			cell = row.createCell(149);
			cell.setCellValue("2.요약CE");
			cell = row.createCell(150);
			cell.setCellValue("2.요약MSP");
			cell = row.createCell(151);
			cell.setCellValue("3.요약CE");
			cell = row.createCell(152);
			cell.setCellValue("3.요약MSP");
			cell = row.createCell(153);
			cell.setCellValue("4.요약CE");
			cell = row.createCell(154);
			cell.setCellValue("4.요약MSP");
			cell = row.createCell(155);
			cell.setCellValue("5.요약CE");
			cell = row.createCell(156);
			cell.setCellValue("5.요약MSP");
			cell = row.createCell(157);
			cell.setCellValue("1.요약CE");
			cell = row.createCell(158);
			cell.setCellValue("1.요약MSP");
			cell = row.createCell(159);
			cell.setCellValue("2.요약CE");
			cell = row.createCell(160);
			cell.setCellValue("2.요약MSP");
			cell = row.createCell(161);
			cell.setCellValue("3.요약CE");
			cell = row.createCell(162);
			cell.setCellValue("3.요약MSP");
			cell = row.createCell(163);
			cell.setCellValue("1.요약CE");
			cell = row.createCell(164);
			cell.setCellValue("1.요약MSP");
			cell = row.createCell(165);
			cell.setCellValue("2.요약CE");
			cell = row.createCell(166);
			cell.setCellValue("2.요약MSP");
			cell = row.createCell(167);
			cell.setCellValue("3.요약CE");
			cell = row.createCell(168);
			cell.setCellValue("3.요약MSP");
			cell = row.createCell(169);
			cell.setCellValue("4.요약CE");
			cell = row.createCell(170);
			cell.setCellValue("4.요약MSP");
			cell = row.createCell(171);
			cell.setCellValue("5.요약CE");
			cell = row.createCell(172);
			cell.setCellValue("5.요약MSP");
			cell = row.createCell(173);
			cell.setCellValue("6.a 요약CE");
			cell = row.createCell(174);
			cell.setCellValue("6.a 요약MSP");
			cell = row.createCell(175);
			cell.setCellValue("6.b 요약CE");
			cell = row.createCell(176);
			cell.setCellValue("6.b 요약MSP");
			cell = row.createCell(177);
			cell.setCellValue("6.c 요약CE");
			cell = row.createCell(178);
			cell.setCellValue("6.c 요약MSP");
			cell = row.createCell(179);
			cell.setCellValue("7.a 요약CE");
			cell = row.createCell(180);
			cell.setCellValue("7.a 요약MSP");
			cell = row.createCell(181);
			cell.setCellValue("7.b 요약CE");
			cell = row.createCell(182);
			cell.setCellValue("7.b 요약MSP");
			cell = row.createCell(183);
			cell.setCellValue("8.a 요약CE");
			cell = row.createCell(184);
			cell.setCellValue("8.a 요약MSP");
			cell = row.createCell(185);
			cell.setCellValue("8.b 요약CE");
			cell = row.createCell(186);
			cell.setCellValue("8.b 요약MSP");
			cell = row.createCell(187);
			cell.setCellValue("9.a 요약CE");
			cell = row.createCell(188);
			cell.setCellValue("9.a 요약MSP");
			cell = row.createCell(189);
			cell.setCellValue("9.b 요약CE");
			cell = row.createCell(190);
			cell.setCellValue("9.b 요약MSP");

		}
	}

	@Override
	public void mapRow(Row row, NeuropsyS1VO vo) {
		Cell cell = null;
		int i = 0;

		cell = row.createCell(i++);
		cell.setCellValue(vo.getTargetId());

		cell = row.createCell(i++);
		cell.setCellValue(vo.getSex());

		cell = row.createCell(i++);
		cell.setCellValue(vo.getProtocol());
		
		cell = row.createCell(i++);
		cell.setCellValue(vo.getPerformCntNm());

		cell = row.createCell(i++);
		cell.setCellValue(vo.getAge());

		cell = row.createCell(i++);
		cell.setCellValue(vo.getS1ExecDate());
		
		cell = row.createCell(i++);
		cell.setCellValue(vo.getTicSubtype());

		cell = row.createCell(i++);
		cell.setCellValue(vo.getS1ExecDate());

		cell = row.createCell(i++);
		cell.setCellValue(vo.getFsiq());
		
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKediwaisVocaOs());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKediwaisArithOs());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKediwaisOrderOs());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKediwaisPieceOs());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKediwaisVocaEs());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKediwaisArithEs());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKediwaisOrderEs());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKediwaisPieceEs());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivCos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivVos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivUos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivPos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivCpos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivMos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivNos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivScos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivSos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivStos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivCes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivVes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivUes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivPes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivCpes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivMes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivNes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivSces());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivSes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivStes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivSios());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivVcos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivInos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivBdos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivMros());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivVpos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivDsos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivAros());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivSsos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivCdos());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivSies());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivVces());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivInes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivBdes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivMres());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivVpes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivDses());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivAres());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivSses());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKwiscivCdes());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsBlues());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsAnger());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsLossm());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsDeath());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsSuicide());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsSuiSeverity());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsSuiCriticality());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsSelfharm());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsUplift());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsDecSleep());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsGoalActivity());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsGallop());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsHallucination());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsDelusion());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsPanic());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsSeparationFear());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsAttachFear());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsRejectSchool());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsSleepFear());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsAloneFear());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsAtrophy());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsSituationFear());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsPain());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsAvoid());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsFutureWorry());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsBodyComplain());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsSelfConsious());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsTension());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsComplusiveAct());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsComplusiveThink());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsPeeNight());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsPeeDay());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsPeeTotal());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsShitNight());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsShitDay());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsShitTotal());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsFatFear());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsLowWeight());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsWeightLoss());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsVoracity());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsAdhdCf());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsAdhdEd());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsAdhdSf());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsAdhdImpulsivity());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsOddAngry());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsOddAa());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsOddNotrules());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsCdLie());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsCdTruancy());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsCdFight());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsCdTorment());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsCdThievery());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsExerciseTic());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getKsadsExerciseVoice());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getGas());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq1Mistake());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq2Notlisten());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq3FollowDiff());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq4ArrangeDiff());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq5AssignAvoid());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq6LostItem());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq7Forgetfulness());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq8Unrest());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq9Overrun());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq10EndlessAct());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq11SilentDiff());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq12SuddenAns());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq13WaitDiff());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq14Interrupt());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq15Fickle());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq16Chatter());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getAdhdrq17DangerAct());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getDiagnosis());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getDiagnosisEtc());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic1Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic1Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic2Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic2Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic3Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic3Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic4Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic4Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic5Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic5Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic6Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic6Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic7Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic7Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic8Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSactTic8Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic1Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic1Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic2Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic2Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic3Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic3Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic4Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic4Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic5Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCactTic5Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSvoiceTic1Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSvoiceTic1Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSvoiceTic2Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSvoiceTic2Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSvoiceTic3Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getSvoiceTic3Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic1Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic1Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic2Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic2Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic3Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic3Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic4Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic4Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic5Ce());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic5Msp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic6aCe());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic6aMsp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic6bCe());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic6bMsp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic6cCe());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getCvoiceTic6cMsp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getTourette7aCe());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getTourette7aMsp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getTourette7bCe());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getTourette7bMsp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getChronicTic8aCe());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getChronicTic8aMsp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getChronicTic8bCe());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getChronicTic8bMsp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getDailyTic9aCe());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getDailyTic9aMsp());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getDailyTic9bCe());
		cell = row.createCell(i++);
		cell.setCellValue(vo.getDailyTic9bMsp());

	}

	@Override
	public void cellMerge(Sheet sheet) {
		//병합 영역 설정
		sheet.addMergedRegion(new CellRangeAddress(0, 0, 9, 16));
		sheet.addMergedRegion(new CellRangeAddress(0, 0, 17, 36));
		sheet.addMergedRegion(new CellRangeAddress(0, 0, 37, 56));
		sheet.addMergedRegion(new CellRangeAddress(0, 0, 57, 130));
		sheet.addMergedRegion(new CellRangeAddress(0, 0, 131, 190));
		sheet.addMergedRegion(new CellRangeAddress(0, 2, 0, 0));
		sheet.addMergedRegion(new CellRangeAddress(0, 2, 1, 1));
		sheet.addMergedRegion(new CellRangeAddress(0, 2, 2, 2));
		sheet.addMergedRegion(new CellRangeAddress(0, 2, 3, 3));
		sheet.addMergedRegion(new CellRangeAddress(0, 2, 4, 4));
		sheet.addMergedRegion(new CellRangeAddress(0, 2, 5, 5));
		sheet.addMergedRegion(new CellRangeAddress(0, 2, 6, 6));
		sheet.addMergedRegion(new CellRangeAddress(0, 2, 7, 7));
		sheet.addMergedRegion(new CellRangeAddress(0, 2, 8, 8));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 9, 12));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 13, 16));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 17, 26));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 27, 36));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 37, 46));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 47, 56));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 57, 64));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 65, 68));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 69, 70));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 72, 76));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 77, 78));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 79, 80));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 81, 84));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 85, 86));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 87, 92));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 97, 100));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 101, 103));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 104, 108));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 109, 110));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 112, 128));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 131, 146));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 147, 156));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 157, 162));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 163, 178));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 179, 182));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 183, 186));
		sheet.addMergedRegion(new CellRangeAddress(1, 1, 187, 190));
		sheet.addMergedRegion(new CellRangeAddress(1, 2, 93, 93));
		sheet.addMergedRegion(new CellRangeAddress(1, 2, 94, 94));
		sheet.addMergedRegion(new CellRangeAddress(1, 2, 95, 95));
		sheet.addMergedRegion(new CellRangeAddress(1, 2, 96, 96));
		sheet.addMergedRegion(new CellRangeAddress(1, 2, 111, 111));

		
	}

	
}
